Repository NibiruChain/cw-nibiru, pull requests merged in 2023-06, with the labels that each got.

#36 feat(bindings-perp): implement ExecuteMsg::Claim handler
  artifacts/bindings_perp.wasm
  artifacts/checksums.txt
  artifacts/checksums_intermediate.txt
  contracts/bindings-perp/src/contract.rs
  contracts/bindings-perp/src/msg.rs
Labels: type: enhancement

#37 fix,test(controller): fix members state change in ChangeAdmin execute handler
  artifacts/checksums.txt
  artifacts/checksums_intermediate.txt
  artifacts/controller.wasm
  contracts/controller/src/contract.rs
Labels: type: bug/fix, type: test

#38 fix,test(shifter): fix members state change in ChangeAdmin execute handler
  .github/workflows/rust-test.yml
  artifacts/checksums.txt
  artifacts/checksums_intermediate.txt
  artifacts/shifter.wasm
  contracts/shifter/src/contract.rs
Labels: type: bug/fix, type: test

#39 refactor(perp): remove trading limits
  Cargo.lock
  artifacts/bindings_perp.wasm
  artifacts/checksums.txt
  artifacts/checksums_intermediate.txt
  artifacts/controller.wasm
  artifacts/shifter.wasm
  contracts/bindings-perp/Cargo.toml
  contracts/bindings-perp/query_resp.json
  packages/bindings/Cargo.toml
  packages/bindings/src/state.rs
  packages/dummy/query_resp.json
  packages/dummy/src/query.rs
Labels: type: refactor

#40 feat,test(bindings-perp): add sudoers checks on each execute msg
  artifacts/bindings_perp.wasm
  artifacts/checksums.txt
  artifacts/checksums_intermediate.txt
  contracts/bindings-perp/src/contract.rs
Labels: type: enhancement, type: test
